### ISSUE TITLE
判断线段相交的时候，怎么样把顶点去掉？

### ISSUE THREAD

**Issue by Xuanwo** [fz568573448/ACM-ICPC-Template#1]
https://github.com/fz568573448/ACM-ICPC-Template/blob/master/%E6%A8%A1%E6%9D%BF/11_%E8%AE%A1%E7%AE%97%E5%87%A0%E4%BD%95/%E8%AE%A1%E7%AE%97%E5%87%A0%E4%BD%95.cpp#L177

**Comment by zheng-fan** [comment]
如果相交，求一下交点，看看交点是不是顶点就行了。

**Comment by fz568573448** [comment]
如果相交，求一下交点，看看交点是不是顶点就行了。

**Comment by Xuanwo** [comment]
@fz568573448 居然一本正经的回复了= =
快卖个萌啊！！
