### ISSUE TITLE
计算几何 圆与多边形相交部分面积 勘误

### ISSUE THREAD

**Issue by Xuanwo** [fz568573448/ACM-ICPC-Template#2]
https://github.com/fz568573448/ACM-ICPC-Template/blob/master/%E6%A8%A1%E6%9D%BF/11_%E8%AE%A1%E7%AE%97%E5%87%A0%E4%BD%95/%E8%AE%A1%E7%AE%97%E5%87%A0%E4%BD%95.cpp#L675

此处应为`fabs(ans)`

详情可参考：http://acm.hust.edu.cn/vjudge/contest/view.action?cid=92377#status/qqcyclone/D/0/

**Comment by zheng-fan** [comment]
polygon类要求输入的点是按逆时针排好。不过加fabs确实是更方便的做法。
